### ISSUE TITLE
Letters before the name in results

### ISSUE THREAD

**Issue by veredrec** [FACN3/Auto-Completer#42]
For better UX I would remove (with a simple function) the one/two capital letters at the beginning of each name. 
e.g. https://github.com/FACN3/Auto-Completer/blob/master/famous_people.txt#L1 
Remove the A and leave `Adele` only. It would make it easier to read :eyeglasses:

**Comment by MynahMarie** [comment]
Done, fixed on Heroku as well :) Your right it's much better for the client side, I decided to keep the list as is for the processing of results so that the function still uses the Initials for searching. I thought it could be a nice option to have search results based on initials as well as full names. :)

**Comment by veredrec** [comment]
Yup, that makes sense! This is of course your decision :+1:
